# Generated by Django 5.0.6 on 2024-06-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_rename_auto_admi_number_institute_auto_admin_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='emp_no_prefix',
            new_name='emp_prefix',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='state',
        ),
    ]
